const TABLE_STATUS = {
  TRONG: 'TRONG',
  DADAT: 'DADAT',
  COKHACH: 'COKHACH',
  CHOTHANHTOAN: 'CHOTHANHTOAN',
  CANDON: 'CANDON',
};

const ORDER_STATUS = {
  CHOCHEBIEN: 'CHOCHEBIEN',
  DANGLAM: 'DANGLAM',
  HOANTHANH: 'HOANTHANH',
  DAPHUCVU: 'DAPHUCVU',
  DAHUY: 'DAHUY',
};

const PAYMENT_METHOD = {
  TIENMAT: 'TienMat',
  THE: 'The',
  QR: 'QR',
  DIEM: 'Diem',
};

module.exports = { TABLE_STATUS, ORDER_STATUS, PAYMENT_METHOD };
