// Permission constants - Các quyền hệ thống
const PERMISSIONS = {
  // Account Management - Chỉ Admin
  ACCOUNT_CREATE: 'ACCOUNT_CREATE',
  ACCOUNT_MANAGE: 'ACCOUNT_MANAGE',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',

  // Reports - Manager, Admin
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Stock/Inventory Management - Manager, Admin, Thu Kho
  STOCK_MANAGE: 'STOCK_MANAGE',
  STOCK_IMPORT: 'STOCK_IMPORT',
  STOCK_VIEW: 'STOCK_VIEW',

  // Menu Management - Manager, Admin
  MENU_MANAGE: 'MENU_MANAGE',
  MENU_CREATE: 'MENU_CREATE',
  MENU_UPDATE: 'MENU_UPDATE',
  MENU_DELETE: 'MENU_DELETE',
  MENU_VIEW: 'MENU_VIEW',

  // Order Management
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_VOID: 'ORDER_VOID',
  ORDER_VOID_APPROVE: 'ORDER_VOID_APPROVE',

  // Payment - Cashier, Admin
  PAYMENT_EXECUTE: 'PAYMENT_EXECUTE',
  PAYMENT_VIEW: 'PAYMENT_VIEW',

  // Shift Management - Cashier, Admin
  SHIFT_MANAGE: 'SHIFT_MANAGE',
  SHIFT_OPEN: 'SHIFT_OPEN',
  SHIFT_CLOSE: 'SHIFT_CLOSE',

  // Kitchen Display System - Kitchen Staff
  KDS_VIEW: 'KDS_VIEW',
  DISH_STATUS_UPDATE: 'DISH_STATUS_UPDATE',  // Bếp: Đang Làm, Xong
  DISH_SERVE: 'DISH_SERVE',                  // PhucVu: Đã Ra

  // Table Management
  TABLE_VIEW: 'TABLE_VIEW',
  TABLE_MANAGE: 'TABLE_MANAGE',

  // Purchase Order - Thu Kho, Manager
  PO_CREATE: 'PO_CREATE',
  PO_APPROVE: 'PO_APPROVE',
  PO_VIEW: 'PO_VIEW',

  // HR Management - Manager, Admin
  HR_MANAGE: 'HR_MANAGE',
  HR_VIEW: 'HR_VIEW',

  // Reservation Management
  RESERVATION_CREATE: 'RESERVATION_CREATE',
  RESERVATION_MANAGE: 'RESERVATION_MANAGE',
  RESERVATION_VIEW: 'RESERVATION_VIEW',

  // Customer Management
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_MANAGE: 'CUSTOMER_MANAGE',

  // Shift Schedule Management - Quản lý ca
  SHIFT_SCHEDULE_VIEW: 'SHIFT_SCHEDULE_VIEW',
  SHIFT_SCHEDULE_MANAGE: 'SHIFT_SCHEDULE_MANAGE',

  // Attendance/Timekeeping - Chấm công
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_MANAGE: 'ATTENDANCE_MANAGE',
};

// Role constants
const ROLES = {
  ADMIN: 'Admin',
  QUAN_LY: 'QuanLy',
  THU_NGAN: 'ThuNgan',
  PHUC_VU: 'PhucVu',
  BEP: 'Bep',
  THU_KHO: 'ThuKho',
};

// Permission sets by role
const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    // Admin có toàn quyền
    PERMISSIONS.ACCOUNT_CREATE,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.ACCOUNT_DELETE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.STOCK_MANAGE,
    PERMISSIONS.STOCK_IMPORT,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.MENU_CREATE,
    PERMISSIONS.MENU_UPDATE,
    PERMISSIONS.MENU_DELETE,
    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_VOID,
    PERMISSIONS.ORDER_VOID_APPROVE,
    PERMISSIONS.PAYMENT_EXECUTE,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.SHIFT_OPEN,
    PERMISSIONS.SHIFT_CLOSE,
    PERMISSIONS.KDS_VIEW,
    PERMISSIONS.DISH_STATUS_UPDATE,
    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_MANAGE,
    PERMISSIONS.PO_CREATE,
    PERMISSIONS.PO_APPROVE,
    PERMISSIONS.PO_VIEW,
    PERMISSIONS.HR_MANAGE,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_MANAGE,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,
    PERMISSIONS.SHIFT_SCHEDULE_VIEW,
    PERMISSIONS.SHIFT_SCHEDULE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
  ],

  [ROLES.QUAN_LY]: [
    // Manager - Quản lý
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.STOCK_MANAGE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.MENU_CREATE,
    PERMISSIONS.MENU_UPDATE,
    PERMISSIONS.MENU_DELETE,
    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.ORDER_VOID_APPROVE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.HR_MANAGE,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.PO_APPROVE,
    PERMISSIONS.PO_VIEW,
    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_MANAGE,
    PERMISSIONS.RESERVATION_MANAGE,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,
    PERMISSIONS.SHIFT_SCHEDULE_VIEW,
    PERMISSIONS.SHIFT_SCHEDULE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
  ],

  [ROLES.THU_NGAN]: [
    // Cashier - Thu ngân
    PERMISSIONS.PAYMENT_EXECUTE,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.SHIFT_OPEN,
    PERMISSIONS.SHIFT_CLOSE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
  ],

  [ROLES.PHUC_VU]: [
    // Server - Phục vụ
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.KDS_VIEW,         // Xem KDS để biết món nào sẵn sàng
    PERMISSIONS.DISH_SERVE,       // Bấm "Đã Ra" khi phục vụ món
  ],

  [ROLES.BEP]: [
    // Kitchen Staff - Bếp
    PERMISSIONS.KDS_VIEW,
    PERMISSIONS.DISH_STATUS_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.MENU_VIEW,
  ],

  [ROLES.THU_KHO]: [
    // Inventory Staff - Thủ kho
    PERMISSIONS.STOCK_IMPORT,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.PO_CREATE,
    PERMISSIONS.PO_VIEW,
    PERMISSIONS.MENU_VIEW,
  ],
};

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
};
